---
networks:
  chatbox:
    external: false

services:
  chatbox:
    #build:
    # context: .
    image: ghcr.io/gottaeat/chatbox:latest
    container_name: chatbox
    hostname: chatbox
    tty: true
    restart: unless-stopped
    environment:
      PUBKEY: <pubkey here>
    networks:
      - chatbox
    volumes:
      - ./data:/data
    ports:
      - 2222:2222
