---
networks:
  irc:
    external: false

services:
  irc:
    #build:
    # context: .
    image: ghcr.io/gottaeat/irc-docker:latest
    container_name: irc
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - irc
    volumes:
      - ${DATA_DIR}:/data
    ports:
      - 3132:3132
