---
networks:
  irc:
    external: false

services:
  irc:
    #build:
    # context: .
    image: ghcr.io/gottaeat/irc-docker:latest
    container_name: irc
    hostname: irc
    tty: true
    restart: unless-stopped
    environment:
      PUBKEY: <pubkey here>
    networks:
      - irc
    volumes:
      - ./data:/data
    ports:
      - 2222:2222
