#!/bin/sh
evalret(){
    local exitval="${?}"

    if [ "${?}" -eq 0 ]
        then
            echo "INFO: success."
        else
            echo "ERROR: failed, exiting!"
            exit 1
    fi
}

shutdown() {
    pinfo "caught SIGTERM/SIGINT, gracefully shutting down."

    irssi_pid="$(pidof irssi)"
    tmux_pid="$(pidof tmux)"
    sshd_pid="$(pidof sshd)"

    for pid in ${irssi_pid} ${tmux_pid} ${sshd_pid}; do
        pinfo "killing ${pid}"
        kill -TERM "${pid}" || true
    done

    exit 0
}

pinfo(){ echo "INFO: ${@}";}
pwarn(){ echo "WARN: ${@}";}
perr(){ echo "ERR : ${@}"; exit 1;}
